name: Show Commit Message

on:
  push:
    branches:
      - main

jobs:
  show-commit-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print commit message
        run: |
          echo "Commit SHA: ${{ github.sha }}"
          echo "Commit message: ${{ github.event.head_commit.message }}"
